### ISSUE TITLE
investigate `PredictGoal`'s `list index out of range`

### ISSUE THREAD

**Issue by rayvburn** [rayvburn/cohan_planner_people_interface#3]
Does it come from the interface or is caused by bad processing of data in [`human_path_prediction`](https://github.com/sphanit/CoHAN_Planner/tree/master/human_path_prediction)?

```console
[ERROR] [1677593669.561970]: bad callback: <bound method PredictGoal.tracked_humansCB of <__main__.PredictGoal object at 0x7f7da810efd0>>
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/pal/.jkarwowski/ws_ros/src/social_nav/cohan/cohan_planner/human_path_prediction/scripts/predict_goal.py", line 56, in tracked_humansCB
    self.current_poses[human.track_id-1].append(segment.pose.pose)
IndexError: list index out of range
```

**Comment by rayvburn** [comment]
This issue is quite common, seems to occur when robot starts to oscillate:

```console
[ WARN] [1677778065.783723548]: HATebLocalPlannerROS: trajectory is not feasible. Resetting planner...
[ WARN] [1677778069.481808554]: HATebLocalPlannerROS: possible oscillation (of the robot or its local plan) detected. Activating recovery strategy (prefer current turning direction during optimization).
[ WARN] [1677778078.581102607]: Clearing both costmaps to unstuck robot (3.00m).
[ INFO] [1677778081.481918750]: HATebLocalPlannerROS: oscillation recovery disabled/expired.
[ERROR] [1677778087.229922]: bad callback: <bound method PredictGoal.tracked_humansCB of <__main__.PredictGoal object at 0x7f3f174f4050>>
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/pal/.jkarwowski/ws_ros/src/social_nav/cohan/cohan_planner/human_path_prediction/scripts/predict_goal.py", line 56, in tracked_humansCB
    self.current_poses[human.track_id-1].append(segment.pose.pose)
IndexError: list index out of range
```
